configured_endpoints: 18
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/riza%2Friza-api-bab65e0b0c2b228ee407ddd78cdcd7f3708bac6d00c0ada71efc6eef73de20fe.yml
openapi_spec_hash: 08c3a26bba78a202f09b51c2d4eb0001
config_hash: cba1727a13fc23eaeb011480ac88a06d
