configured_endpoints: 15
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/riza%2Friza-api-bab65e0b0c2b228ee407ddd78cdcd7f3708bac6d00c0ada71efc6eef73de20fe.yml
openapi_spec_hash: 08c3a26bba78a202f09b51c2d4eb0001
config_hash: 8ac0e6ef0ce0f5388eed4f14e515a7c9
